dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "9"
cache:
  yarn: true
env:
  -
  # - SOLIDITY_COVERAGE=true FIXME: disabled because of versions conflicts
matrix:
  fast_finish: true
  # allow_failures:
  #   - env: SOLIDITY_COVERAGE=true
before_script:
 - chmod +x ./scripts/ci.sh
script:
  - yarn lint
  - ./scripts/ci.sh
